In [1]:
import torch
torch.cuda.is_available()

True

In [7]:
import pandas as pd 

df = pd.read_csv('synthetic_physiological_data/physiological_synthetic_data.csv')
df

,HRV_MeanNN,HRV_SDNN,HRV_SDANN1,HRV_SDNNI1,HRV_RMSSD,HRV_SDSD,HRV_CVNN,HRV_CVSD,HRV_MedianNN,HRV_MadNN,...,p85,p90,p95,p100,p105,p114_t1,isi30,isi60,isi120,CAPSF1I2s.0
0,775.0,73.0,20.0,70.0,50.0,50.0,0.09,0.06,780.0,55.0,...,15.5,10.0,13.5,21.0,66.0,117.0,50.0,38.0,60.0,0.0
1,980.0,44.0,17.0,41.0,46.0,46.0,0.04,0.04,985.0,46.0,...,14.5,11.0,22.0,11.5,19.0,485.0,36.0,50.0,36.0,0.0
2,840.0,58.0,39.0,47.0,47.0,47.0,0.07,0.06,835.0,50.0,...,15.5,81.0,165.0,201.0,247.0,513.0,75.0,88.0,87.0,0.0
3,1025.0,105.0,48.0,82.0,85.0,85.0,0.11,0.09,1020.0,50.0,...,47.0,52.0,61.0,127.0,206.0,492.0,49.0,43.0,69.0,0.0
4,835.0,40.0,13.0,38.0,40.0,40.0,0.05,0.05,830.0,42.0,...,87.0,185.0,710.0,890.0,1065.0,663.0,-28.0,-10.0,11.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497,845.0,52.0,8.0,51.0,44.0,44.0,0.06,0.05,850.0,48.0,...,14.0,72.0,236.0,250.0,460.0,810.0,-45.0,27.0,10.0,1.0
498,980.0,110.0,53.0,100.0,82.0,83.0,0.11,0.08,980.0,110.0,...,14.0,12.0,63.0,42.0,135.0,470.0,73.0,39.0,67.0,1.0
499,760.0,37.0,20.0,32.0,22.0,22.0,0.05,0.03,765.0,34.0,...,11.0,12.0,14.0,20.0,35.0,28.0,36.0,-9.0,51.0,1.0
500,870.0,75.0,33.0,68.0,68.0,67.0,0.09,0.08,870.0,75.0,...,7.0,12.0,22.0,167.0,115.0,245.0,34.0,24.0,34.0,1.0
501,840.0,63.0,9.0,59.0,75.0,76.0,0.07,0.09,850.0,27.0,...,22.0,22.0,52.0,138.0,129.0,237.0,63.0,66.0,82.0,1.0

In [8]:
df['CAPSF1I2s.0'].value_counts()

CAPSF1I2s.0
1.0    267
0.0    235
Name: count, dtype: int64

In [5]:
# remove nan rows and rows with CAPSF1I2s.0 != 0 or 1

import pandas as pd 

df = pd.read_csv('synthetic_physiological_data/physiological_synthetic_data.csv')
df = df[df['CAPSF1I2s.0'].isin([0, 1])]
df = df.dropna()
df

,HRV_MeanNN,HRV_SDNN,HRV_SDANN1,HRV_SDNNI1,HRV_RMSSD,HRV_SDSD,HRV_CVNN,HRV_CVSD,HRV_MedianNN,HRV_MadNN,...,p85,p90,p95,p100,p105,p114_t1,isi30,isi60,isi120,CAPSF1I2s.0
0,775.0,73.0,20.0,70.0,50.0,50.0,0.09,0.06,780.0,55.0,...,15.5,10.0,13.5,21.0,66.0,117.0,50.0,38.0,60.0,0.0
1,980.0,44.0,17.0,41.0,46.0,46.0,0.04,0.04,985.0,46.0,...,14.5,11.0,22.0,11.5,19.0,485.0,36.0,50.0,36.0,0.0
2,840.0,58.0,39.0,47.0,47.0,47.0,0.07,0.06,835.0,50.0,...,15.5,81.0,165.0,201.0,247.0,513.0,75.0,88.0,87.0,0.0
3,1025.0,105.0,48.0,82.0,85.0,85.0,0.11,0.09,1020.0,50.0,...,47.0,52.0,61.0,127.0,206.0,492.0,49.0,43.0,69.0,0.0
4,835.0,40.0,13.0,38.0,40.0,40.0,0.05,0.05,830.0,42.0,...,87.0,185.0,710.0,890.0,1065.0,663.0,-28.0,-10.0,11.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
507,845.0,52.0,8.0,51.0,44.0,44.0,0.06,0.05,850.0,48.0,...,14.0,72.0,236.0,250.0,460.0,810.0,-45.0,27.0,10.0,1.0
508,980.0,110.0,53.0,100.0,82.0,83.0,0.11,0.08,980.0,110.0,...,14.0,12.0,63.0,42.0,135.0,470.0,73.0,39.0,67.0,1.0
509,760.0,37.0,20.0,32.0,22.0,22.0,0.05,0.03,765.0,34.0,...,11.0,12.0,14.0,20.0,35.0,28.0,36.0,-9.0,51.0,1.0
510,870.0,75.0,33.0,68.0,68.0,67.0,0.09,0.08,870.0,75.0,...,7.0,12.0,22.0,167.0,115.0,245.0,34.0,24.0,34.0,1.0
511,840.0,63.0,9.0,59.0,75.0,76.0,0.07,0.09,850.0,27.0,...,22.0,22.0,52.0,138.0,129.0,237.0,63.0,66.0,82.0,1.0

In [6]:
df.to_csv('synthetic_physiological_data/physiological_synthetic_data.csv', index=False)

In [3]:
import pickle

with open('pre_deployment_data.pkl', 'rb') as f:
    data_dict = pickle.load(f)

merged_df = data_dict['merged_df']
HRV_features = data_dict['HRV_features']
EMG_features = data_dict['EMG_features']
CUT_features = data_dict['CUT_feature']
SPSS_features = data_dict['SPSS_feature']
categorical_features = data_dict['categorical_features']
PTSD_features = data_dict['PTSD_features']

data_dict['numeric_features']

features_cut = ['age','pCRP','pNPY','uE','uNE','sCortisol','sAlpha_Amylase','sCotinine',\
             'systolic_use','diastolic_use','BMI','waist','MAP']

# Find features that are in both data_dict['numeric_features'] and features_cut
common_features = [f for f in features_cut if f in data_dict['numeric_features']]
print("Features in both lists:", common_features)

Features in both lists: ['age', 'pCRP', 'pNPY', 'uE', 'uNE', 'sCortisol', 'sAlpha_Amylase', 'sCotinine', 'systolic_use', 'diastolic_use', 'BMI', 'waist', 'MAP']

In [4]:
len(common_features), len(features_cut)

(13, 13)

In [5]:
list1 = ['string1', 'string2'] 
list2 = ['string1']

for f in list1:
    for i in list2:
        if i == f:
            list1.remove(f)

In [6]:
list1

['string2']

In [1]:
import pickle

with open('combined.pkl', 'rb') as f:
    data_dict = pickle.load(f)

data_dict

/var/folders/39/1dgv6b0x4lz6pbcy5_ylf5g40000gn/T/ipykernel_31639/3031440455.py:4: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric._frombuffer.
  data_dict = pickle.load(f)

,subjectID,HR_5min,HRnooutliers,VLF,LF,HF,lnVLF,lnHF,lnLFHF,lnVLFnooutliers,...,Sympathetic_vagalbalance,CAPSF1I2s,CAPSF1I23s_lenient,CAPSF1I2s_stringent,LFHF,pCRP,pNPY,uE,uNE,d_label
0,pre_1000,61.019812,61.019812,2223.766360,6566.874627,3783.721057,7.706958,8.238463,0.551330,7.706958,...,1.735560,0,0,0,1.735560,0.230700,93.065797,4.048067,24.200633,1
1,pre_1001,74.745672,74.745672,2579.528181,4425.009953,6010.148870,7.855362,8.701205,-0.306177,7.855362,...,0.736256,0,0,0,0.736256,1.579300,49.381889,12.135511,66.755474,1
2,pre_1002,65.880525,65.880525,3040.564853,4787.981107,2010.529916,8.019799,7.606154,0.867710,8.019799,...,2.381452,0,0,0,2.381452,0.941900,40.963085,2.605511,32.773094,0
3,pre_1003,75.759202,75.759202,3147.879519,15934.098692,5556.313489,8.054484,8.622690,1.053527,8.054484,...,2.867747,0,0,0,2.867747,0.280500,300.000000,21.307110,63.767052,1
4,pre_1004,66.493104,66.493104,4422.193500,4186.470036,1720.385080,8.394391,7.450303,0.889310,8.394391,...,2.433449,0,0,0,2.433449,1.268700,75.086531,2.797750,14.154675,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5225,post_5041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,NaN,0.716546,102.036117,7.665486,79.198051,1
5226,post_5044,77.017760,77.017760,475.071921,1138.407864,1967.180402,6.163466,7.584357,-0.546971,6.163466,...,0.578700,0,1,1,0.578700,3.196965,91.979048,11.063013,50.288230,1
5227,post_5045,78.997664,78.997664,636.047327,2114.217919,1031.899202,6.455273,6.939156,0.717284,6.455273,...,2.048861,0,0,0,2.048861,20.476028,75.746901,1.228593,95.689501,1
5228,post_5046,63.483106,63.483106,2984.577354,3753.850141,2567.321229,8.001213,7.850618,0.379919,8.001213,...,1.462166,0,0,0,1.462166,2.221943,99.033773,11.906006,70.376080,0
5229,post_5047,52.725968,52.725968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,NaN,0.133438,86.821969,8.375403,31.978890,1